name: PR release
on :
  workflow_dispatch:
  pull_request_target:
    branches:
      - 'release/**'

jobs:
  build:
    name: Release detection
    runs-on: ubuntu-latest
    steps:
      - name: Bash commands
        run: |
          echo ${{ github.base_ref }}
      - name: Relase detector
        if: contains(github.base_ref, 'main')
        run: |
          echo "release detected (new)" 


