name: PR release
on :
  create:

jobs:
  build:
    name: Release detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bash commands
        if: contains(github.ref, '/release-')
        run: |
          echo "release detected (new)"
          echo ${{ github.ref }}


