name: PR release
on :
  create:
    paths:
      - '**/release-**'

jobs:
  build:
    name: Release detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bash commands
        run: |
          "echo release detected"


