name: PR run

on :
  create:
    branches: [release-*]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        run: |
          "echo release detected"


