name: PR release
on :
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Release detection
    runs-on: ubuntu-latest
    steps:
      - name: Bash commands
        run: |
          echo ${{ github.ref }}
      - name: Relase detector
        if: contains(github.ref, 'release/')
        run: |
          echo "release detected (new)" 


