name: PR release
on :
  pull_request:
    branches:
      - 'release/**'

jobs:
  build:
    name: Release detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bash commands
        run: |
          echo "release detected (new)"
          echo ${{ github.ref }}


