name: PR release
on :
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Release detection
    if: contains(github.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bash commands
        run: |
          echo "release detected (new)"
          echo ${{ github.ref }}


