name: PR check

on :
  workflow_dispatch:
  pull_request:
   branches: 
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Git commands
      run: |
        git --version
        git status
        git branch

    - name: Setup JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.5'
        bundler-cache: true


